### ISSUE TITLE
Model with "audited" gem raise an error on save

### ISSUE THREAD

**Issue by taufek** [DmitryTsepelev/store_model#82]
I'm getting below error when using `store_model` with `audited` gem in a model.

```
class Product < Application Record
  audited
  attribute :info, Info.to_type
end

class Info
  include StoreModel::Model

  attribute :name, :string
end

product = Product.new
product.info = { name: 'foo' }
product.save

> NoMethodError: undefined method `to_hash' for nil:NilClass
from /Users/taufek/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activemodel-6.0.3.1/lib/active_model/attributes.rb:97:in `attributes'

```

**Comment by taufek** [comment]
Found a workaround by excluding the jsonb column from `audited`. 

In example above I need to do 
```
class Product < Application Record
  audited except: :info
  attribute :info, Info.to_type
end
```

**Comment by DmitryTsepelev** [comment]
Interesting, could you please post the whole stack trace? And also the output of `product.info.attributes.to_hash` and `product.attributes.to_hash`

**Comment by taufek** [comment]
Spec:
```
RSpec.describe Product, type: :model do
  it 'creates Product' do
    product = Product.new
    product.info = { name: 'Dyson' }
    product.save

    expect(product).to be_persisted
  end
end

```

Output:
```
Failures:

  1) Product creates Product
     Failure/Error: product.save

     NoMethodError:
       undefined method `to_hash' for nil:NilClass
     # /usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/audited-4.10.0/lib/audited/audit.rb:20:in `load'
     # /usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/audited-4.10.0/lib/audited/auditor.rb:310:in `block in write_audit'
     # /usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/audited-4.10.0/lib/audited/auditor.rb:309:in `write_audit'
     # /usr/local/Cellar/tmuxinator/2.0.1/libexec/gems/audited-4.10.0/lib/audited/auditor.rb:288:in `audit_create'
     # ./spec/models/product_spec.rb:7:in `block (2 levels) in <main>'

```
